import torch
import torch.nn as nn
from utils import rgb_to_yuv, gram_matrix
from model.vgg import Vgg19

class ColorLoss(nn.Module):
    def __init__(self):
        super(ColorLoss, self).__init__()
        self.l1_loss = nn.L1Loss()
        self.huber_loss = nn.SmoothL1Loss()
    
    def forward(self, img, img_g):
        """
        Args:
            img : training photo
            img_g : image generated by Generator
        """
        # convert img from rgb -> yuv format
        img = rgb_to_yuv(img)
        img_g = rgb_to_yuv(img_g)

        return self.l1_loss(img[:, :, :, 0], img_g[:, :, :, 0]) + self.huber_loss(img[:, :, :, 1], img_g[:, :, :, 1]) + self.huber_loss(img[:, :, :, 2], img_g[:, :, :, 2])
    

class AnimeLoss:
    def __init__(self, device, w_adv_g, w_adv_d, w_con, w_gra, w_col):
        self.w_adv_g = w_adv_g
        self.w_adv_d = w_adv_d
        self.w_con = w_con
        self.w_gra = w_gra
        self.w_col = w_col
        self.vgg_19 = Vgg19().to(device).eval()
        self.content_loss = nn.L1Loss().to(device)
        self.gram_loss = nn.L1Loss().to(device)
        self.color_loss = ColorLoss().to(device)

    def g_loss(self, img, img_g, fake_logit, anime_gray):
        """

        Args:
            img : training photo
            img_g : img generated by G(training photo)
            fake_logit : D(G(training_photo))
            anime_gray : anime gray scale
        """
        img_feat = self.vgg_19(img)
        img_g_feat = self.vgg_19(img_g)
        anime_gray_feat = self.vgg_19(anime_gray)
        return self.w_adv_g * self.l_adv_g(fake_logit) + self.w_con * self.l_con(img_feat, img_g_feat) + self.w_gra * self.l_gra(img_g_feat, anime_gray_feat) + self.w_col * self.color_loss(img, img_g)

    def d_loss(self, real_anime_logit, fake_logit, real_anime_gray_logit, real_anime_smooth_gray_logit):
        """

        Args:
            real_anime_logit : D(anime_img)
            fake_logit : D(G(img))
            real_anime_gray_logit : D(anime_gray)
            real_anime_smooth_gray_logit : D(anime_gray_smooth)
        """
        return self.w_adv_d * (
            self.l_adv_d_real(real_anime_logit) +
            self.l_adv_d_fake(fake_logit) +
            self.l_adv_d_fake(real_anime_gray_logit) +
            0.1 * self.l_adv_d_fake(real_anime_smooth_gray_logit)
        )

    def l_con(self, img_feat, img_g_feat):
        """

        Args:
            img : training photo features (extracted by vgg19)
            img_g : image generated features (extracted by vgg19) by Generator
        """
        return self.content_loss(img_feat, img_g_feat)

    def l_gra(self, img_g_feat, anime_gray_feat):
        """

        Args:
            img_g_feat : image generated features (extracted by vgg19) by Generator
            anime_gray_feat : anime gray features (extracted by vgg19)
        """
        return self.gram_loss(gram_matrix(anime_gray_feat), gram_matrix(img_g_feat))
    
    def l_col(self, img, img_g):
        """

        Args:
            img : training photo
            img_g : image generated by Generator
        """
        return self.color_loss(img, img_g)

    def l_adv_g(self, fake_logit):
        """

        Args:
            fake_logit : output of D given by img_g ( img_g = G(img) )
        """
        return torch.mean(torch.square(fake_logit-1.0))
    
    def l_adv_d_real(self, real_anime_logit):
        """

        Args:
            real_logit : output of D given by anime img
        """
        return torch.mean(torch.square(real_anime_logit-1.0))
    
    def l_adv_d_fake(self, fake_logit):
        """

        Args:
            fake_logit : output of D given by img_g ( img_g = G(img) ) , anime_gray and anime_smooth_gray
        """
        return torch.mean(torch.square(fake_logit-0.0))
